policy_c_sources = files('PSTRuntimePolicyValidation.c')
policy_type_sources = files('PSTRuntimePolicyTypes.c')
policy_objc_sources = files('PSTRuntimePolicy.m')
policy_sources = policy_c_sources + policy_objc_sources

policy_headers = files(
    'PSTRuntimePolicy.h',
    'PSTRuntimePolicyTypes.h',
    'PSTRuntimePolicyValidation.h',
)
