security_c_sources = files(
    'PSTCredentialValidator.c',
    'PSTSecureBuffer.c',
    'PSTTrustedProcessValidation.c',
)

security_objc_sources = files('PSTTrustedProcess.m')

security_headers = files(
    'PSTCredentialValidator.h',
    'PSTSecureBuffer.h',
    'PSTTrustedProcess.h',
    'PSTTrustedProcessTypes.h',
    'PSTTrustedProcessValidation.h',
)
